repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
        additional_dependencies: [click==8.0.2]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.0.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG.rst|HOWTORELEASE.rst|README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
