{% set PY = os.environ['CONDA_PY'] | int %}
name: flask-restalchemy-py{{ PY }}

dependencies:
  {% if PY==36 %}
  - python ==3.6.11
  {% elif PY==310 %}
  - python ==3.10.4  # [win]
  - python ==3.10.2  # [linux]
  {% endif %}
  - sqlalchemy ==1.3.15  # [PY==36]
  - sqlalchemy ==1.4.44  # [PY==310]
  - flask>=1.0
  - sqlalchemy-utils>=0.30
  - flask-sqlalchemy>=2.3.0
  - pytest
  - pytest-regressions
  - pytest-mock>=1.10.0
  - tox

environment:
  PYTHONPATH:
    - {{ root }}/src
    - {{ root }}/../serialchemy/src
