[tox]
envlist = py{38,39,310,311,312}-sqla{14,20}, linting, docs
isolated_build = true

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
extras = testing
commands =
    pytest --cov={envsitepackagesdir}/flask_restalchemy --cov-report=xml --pyargs flask_restalchemy
deps =
    sqla14: sqlalchemy>=1.4,<2
    sqla20: sqlalchemy>=2,<3

[testenv:docs]
skipsdist = True
usedevelop = True
changedir = docs
extras = docs
commands =
    sphinx-build -W -b html . _build


[testenv:linting]
skip_install = True
basepython = python3.10
deps = pre-commit>=1.11.0
commands = pre-commit run --all-files --show-diff-on-failure
