name: build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - name: Upload codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
